### PR TITLE
Testing the board

### LINKED ISSUE #13: Test issue

### PR DESCRIPTION
**Pull request by markusdregi**
*Approach*
Just a PR to test the board.

*Related issues*
Resolves #13

### CODE REVIEW

**Review by pgdr — APPROVED** [review]
Looks ok (except for 4 spaces instead of 2)

**Review by pgdr — APPROVED** [review]
ok

**Review by jepebe — APPROVED** [review]
👍

**Review by jepebe — APPROVED** [review]
🤨

**Pull request closed without merging**
